@startuml
'https://plantuml.com/class-diagram

class SuperHero extends Hero{
    + boolean isFlying
}

interface Attackable {
{abstract} void attack(Slime slime)
}

class House implements Attackable {
}

abstract class Character implements Attackable {
String name

}

class Character{
    String name
    int hp

    {abstract} void attack(Slime slime)
}

class Wizard extends Character{
    int mp
    + void heal(Hero hero)
    + void attack((Slime slime)
}

class Hero extends Character {
    + void attack(Kinoko enemy)
    + void bye()
    - void die()
}

class Cleric{
    + String name
    - int hp
    + int mp

    + void attack(Kinoko enemy)
    + void pray(int sec)
    + void selfAid()
}

@enduml