@startuml
'https://plantuml.com/class-diagram

class SuperHero extends Hero{
    + boolean isFlying
}
class Character{
    String name
    int hp
}

class Wizard extends Character{
    int mp
    + void heal(Hero hero)
}

class Hero extends Character {
    + void attack(Kinoko enemy)
    + void bye()
    - void die()
}

class Cleric{
    + String name
    - int hp
    + int mp

    + void attack(Kinoko enemy)
    + void pray(int sec)
    + void selfAid()
}

@enduml