@startuml
'https://plantuml.com/class-diagram
scale 0.7

class SuperHero extends Hero {
    + boolean isFlying
}

interface Attackable {
    {abstract} void attack(Slime slime)
}

class charcter implements Attackable {
    String name
    int hp

    {abstract} void attack(Slime slime)
}

class Hero {
    + String name
    - int hp

    + void attack(Kinoko enemy)
    + void bye()
    - void die()
}

class Cleric {
    + String name
    - int hp
    + int mp

    + void attack(Kinoko enemy)
    + void pray(int sec)
    + void selfAid()
}

@enduml