@startuml
'https://plantuml.com/class-diagram

scale 1

class Cleric{
}
class PerSon{
}
class Wand{
}
class Wizard{
}
class ClericTest{
}
class WandTest{
}
class WizardTest{
}
class GreatWizard{
}
class Slime{
}
class PoisonSlime{
}
class Hero{
}


@enduml