@startuml
'https://plantuml.com/class-diagram

scale 1

class IntanibleAsset{
    String patent
    String name
}

class TangibleAsset{
    int price
    String color
}

class Book {
    String isbn
}

class Computer {
    String makerName
}

@enduml