@startuml
Scale 1

class Hero {
    - String name
    - int hp
    - int maxHp
}

class Cleric {
    - String name
    - int hp
    - int mp

    + void attack(Kinoko Enemy)
    + void pray(int second)
    + void selfAid()
}

class Wizard {
    - String name
    - int hp
    - int mp
    - Wand wand

    + void heal()
}

class GreatWizard extends Wizard {
    + void heal(Hero hero)
    + void superHeal(Hero hero)
}

class Wand {
    - String name
    - double power
}

class Slime {
    - String suffix
    - int hp

    + void attack(Hero hero)
}

class PoisonSlime extends Slime {
    + void attack(Hero hero)
}

@enduml