@startuml
'https://plantuml.com/class-diagram

scale 1
skinparam classAttributeIconSize 0

class Hero {
    - String name
    - int hp
    - int mp
    - Sword sword

    + Hero(String name, int hp)

    + void getHp()
    + void setHp(int hp)
    + void getMp()
    + void setMp(int mp)
}

class Cleric {
    - String name
    - int hp
    - int mp
    - Random rand
    {static} + int maxHp <<constant>>
    {static} + int maxMp <<constant>>

    + Cleric(String name)
    + Cleric(String name, int hp)
    + Cleric(String name, int hp, int mp)

    + String getName()
    + int getHp()
    + int getMp()

    + void selfAid()
    + int pray(int timePray)
}

class Wand {
    - String name
    - double power

    + String getName()
    + void setName(String name)
    + double power()
    + void setPower(double power)
}

class Wizard {
    - int hp
    - int mp;
    - String name;
    - Wand wand;

    + int getHp()
    + void setHp(int hp)
    + String getName()
    + void setName(String name)
    + Wand getWand()
    + void setWand(Wand wand)
    + void heal(Hero hero)
}

@enduml