@startuml
'https://plantuml.com/class-diagram

abstract class Asset {
-String name;
-int price;
}

class TangibleAsset extends Asset {
-String color;
}

class IntangibleAsset extends Asset {
}

class Book extends TangibleAsset {
-String isbn;
}

class Computer extends TangibleAsset {
-String makerName;
}

class Patent extends IntangibleAsset {
}

@enduml