@startuml
'https://plantuml.com/class-diagram


scale 1
abstract class Asset {
- String name
- int price
}

abstract class TangibleAsset extends Asset implements Thing{


- String color
- double weight
}

class Book extends TangibleAsset {
- String isbn
}

class Computer extends TangibleAsset {
- String makeName
}


abstract class IntangibleAsset extends Asset{
}

interface Thing {
+ double getWeight()
+ void setWeight(double weight)

}

class Patent extends IntangibleAsset {
}

@enduml