@startuml
scale 1.5

interface Thing {
    double getWeight()
    void setWeight(double weight)
}

abstract class Asset {
    String name
    int price
}

abstract class TangibleAsset extends Asset implements Thing {
    String color
    double weight
}

class Book extends TangibleAsset {
    String isbn
}

class Computer extends TangibleAsset {
    String makerName
}

class Patent extends IntangibleAsset

abstract class IntangibleAsset extends Asset {
}
@enduml