@startuml
'https://plantuml.com/class-diagram

scale 1
abstract class Asset {
    String name
}

abstract class IntanibleAsset extends Asset {
    String smell
}

abstract class TangibleAsset extends Asset implements Thing {
    int price
    String color
}

class Book extends TangibleAsset{
    String isbn
}

class Computer extends TangibleAsset{
    String makerName
}

interface Thing {
     {abstract} void setweight(double weight)
     {abstract} void getweight()
}

@enduml