@startuml
'https://plantuml.com/class-diagram

abstract class Asset {
   - String name
   - int price
}

abstract class TangibleAsset extends Asset implements Thing {
    - String color
}

abstract class IntangibleAsset extends Asset {

}

class Computer extends TangibleAsset {
    - String makerName
}

class Book extends TangibleAsset {
    - String isbn
}

class Patent extends IntangibleAsset {

}

interface Thing {
    + void getter(double weight)
    + void setter(double weight)
}

@enduml