@startuml
'https://plantuml.com/class-diagram

scale 1.3

abstract class Asset {
    String name
    int price
}

interface thing {
    double getWeight()
    void setWeight(double weight)
}

abstract class IntangibleAsset extends Asset {

}

abstract class TangibleAsset extends Asset , thing{
    String color
    double weight
}
class Book extends TangibleAsset {
    String isbn
}
class computer extends TangibleAsset {
    String makerName
}
class Patent extends IntangibleAsset {
}


@enduml