@startuml
'https://plantuml.com/class-diagram

class Slime{
    - final String suffix
    - int hp

     + void attack(Hero hero)
}

class PoisonSlime extends Slime{
    - int poisonCount;
    - final int setPoison = 5
    + attack(Hero hero)

}

@enduml