@startuml
'https://plantuml.com/class-diagram

class StrongBox{
    - E data
    - KeyType keyType
    - int count

    + int getCount()
    + void put(E data)
    + E get()
}
+enum KeyType {
    PADLOCK
    BUTTON
    DIAL
    FINGER
}

@enduml