@startuml
'https://plantuml.com/class-diagram

class Wizard {
    -int hp
    -int mp
    -String name
    -Wand wand

    +void heal(Hero hero)
}

class Wand{
    -String name
    -double power
    +Wand()
    +Wand(String name, double power)
}

class GreatWizard extends Wizard{
    - final int defaultMP = 150

    + void heal(Hero hero)
    + void superHeal(Hero hero)
}

@enduml